# Examples

This notebook provides several examples of how to correctly use the library.

At the moment, QudLy allows users to simulate the action of gates on qudits and perform other operations, as well as measure the state itself.



## Initialization

To start working with the library, the first step is to set the dimension of the qudits to be used. This can only be done once and must be completed before creating any states or gates.


In [2]:
import QudLy as q
import numpy as np

q.set_dim(4)

It is now possible to initialize one or more qudits. It is recommended to start with single-qudit states, but it is also possible to directly initialize the total state, provided that its dimension is consistent with the dimension previously set: len(array) = dim^n

The create_state function can be used to combine single-qudit states into the total state.
Regardless of the input vector, it will be automatically normalized.



In [3]:
State_1=q.State([0, 1, 0, 0], 0)
State_2=q.State([0, 0, 1, 0], 1)
State_3=q.State([1, 0, 0, 0], 2)

State=q.create_state([State_1, State_2, State_3])

State_total=q.Total_state([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 1, 0, 0])


print(State)
print(State_total)

[0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[0  0  0.353553  0  0  0  0.353553  0.353553  0  0  0  0.707107  0
 0.353553  0  0]


Once an initial state has been created, gates can be created to act on the qudits.
To create a gate, it is only necessary to specify which qudits it acts on.
It is always possible to display the matrix associated with a gate by printing it.

In [4]:
Gate_1=q.Gate_Z(2)
Gate_2=q.Gate_H(0)

print(Gate_1)
print(Gate_2)

[[1  0  0  0]
 [0  1j  0  0]
 [0  0  -1  0]
 [0  0  0  -1j]]
[[0.5  0.5  0.5  0.5]
 [0.5  0.5j  -0.5  -0.5j]
 [0.5  -0.5  0.5  -0.5]
 [0.5  -0.5j  -0.5  0.5j]]


Once the state and gates to be used have been defined, the gates can be applied to the state using the `apply_gate` function. Given a state and a gate, this function returns the resulting final state.

In [5]:
Final_state=q.apply_gate(State, Gate_1)
Final_state=q.apply_gate(Final_state, Gate_2)

print(Final_state)

[0  0  0  0  0  0  0  0  0.5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0.5j  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  -0.5  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  -0.5j  0  0  0  0  0  0  0]


For a better understanding, you can print the state vector in tensor form using `state.tensor`:



In [6]:
print(Final_state.tensor)

[[[0  0  0  0]
  [0  0  0  0]
  [0.5  0  0  0]
  [0  0  0  0]]

 [[0  0  0  0]
  [0  0  0  0]
  [0.5j  0  0  0]
  [0  0  0  0]]

 [[0  0  0  0]
  [0  0  0  0]
  [-0.5  0  0  0]
  [0  0  0  0]]

 [[0  0  0  0]
  [0  0  0  0]
  [-0.5j  0  0  0]
  [0  0  0  0]]]


The library also includes several operations that are combinations of multiple gates, such as the Quantum Fourier Transform (QFT) and the SWAP operation.



In [7]:
Final_state_2=q.apply_QFT(State)

Final_state_3=q.apply_SWAP(State, 0, 2)

print(Final_state_2)
print(Final_state_3)

[0.125  0.088-0.088j  -0.125j  -0.088-0.088j  -0.125  -0.088+0.088j
 0.125j  0.088+0.088j  0.125  0.088-0.088j  -0.125j  -0.088-0.088j  -0.125
 -0.088+0.088j  0.125j  0.088+0.088j  0.125  0.088-0.088j  -0.125j
 -0.088-0.088j  -0.125  -0.088+0.088j  0.125j  0.088+0.088j  0.125
 0.088-0.088j  -0.125j  -0.088-0.088j  -0.125  -0.088+0.088j  0.125j
 0.088+0.088j  0.125  0.088-0.088j  -0.125j  -0.088-0.088j  -0.125
 -0.088+0.088j  0.125j  0.088+0.088j  0.125  0.088-0.088j  -0.125j
 -0.088-0.088j  -0.125  -0.088+0.088j  0.125j  0.088+0.088j  0.125
 0.088-0.088j  -0.125j  -0.088-0.088j  -0.125  -0.088+0.088j  0.125j
 0.088+0.088j  0.125  0.088-0.088j  -0.125j  -0.088-0.088j  -0.125
 -0.088+0.088j  0.125j  0.088+0.088j]
[0  0  0  0  0  0  0  0  9.94252e-17  1  -1.60658e-16  0  0  0  0  0  0  0
 0  0  0  0  0  0  -1.68389e-16  7.9401e-17  -5.81866e-32  -9.24446e-32  0
 0  0  0  0  0  0  0  0  0  0  0  -6.77927e-32  1.12482e-32  -5.81384e-32
 1.91219e-31  0  0  0  0  0  0  0  0  0  0  0  0  -6.16

Finally, the library allows measurements of either individual qudits or the total state.

The `measure` and `measure_single` functions return an element of the state selected according to the probability associated with each element.

For `measure_single`, by setting `collapse=True`, the function also returns the collapsed state.

In [8]:
measure_1=q.measure(Final_state)

measure_2, Collapsed_state=q.measure_single(Final_state, 0, collapse=True)

print(measure_1)
print(measure_2)
print(Collapsed_state)

[0, 2, 0]
3
[0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  -1j  0  0  0  0  0  0  0]


The `measure_prob` and `measure_prob_single` functions are used to explicitly display the probabilities of the total state or of an individual qudit, respectively.

In [9]:
print(q.measure_prob(Final_state_2))
print(q.measure_prob_single(Final_state_2, 0))

[['|000>', 0.0156], ['|001>', 0.0156], ['|002>', 0.0156], ['|003>', 0.0156], ['|010>', 0.0156], ['|011>', 0.0156], ['|012>', 0.0156], ['|013>', 0.0156], ['|020>', 0.0156], ['|021>', 0.0156], ['|022>', 0.0156], ['|023>', 0.0156], ['|030>', 0.0156], ['|031>', 0.0156], ['|032>', 0.0156], ['|033>', 0.0156], ['|100>', 0.0156], ['|101>', 0.0156], ['|102>', 0.0156], ['|103>', 0.0156], ['|110>', 0.0156], ['|111>', 0.0156], ['|112>', 0.0156], ['|113>', 0.0156], ['|120>', 0.0156], ['|121>', 0.0156], ['|122>', 0.0156], ['|123>', 0.0156], ['|130>', 0.0156], ['|131>', 0.0156], ['|132>', 0.0156], ['|133>', 0.0156], ['|200>', 0.0156], ['|201>', 0.0156], ['|202>', 0.0156], ['|203>', 0.0156], ['|210>', 0.0156], ['|211>', 0.0156], ['|212>', 0.0156], ['|213>', 0.0156], ['|220>', 0.0156], ['|221>', 0.0156], ['|222>', 0.0156], ['|223>', 0.0156], ['|230>', 0.0156], ['|231>', 0.0156], ['|232>', 0.0156], ['|233>', 0.0156], ['|300>', 0.0156], ['|301>', 0.0156], ['|302>', 0.0156], ['|303>', 0.0156], ['|310>', 0